name: Build
run-name: Build

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - 'README.md'
      - '.github/**'
    tags:
      - 'v*'

jobs:
  build:
    strategy:
      matrix:
        os: [ windows-latest, macos-latest, ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install dependencies
        run: |
          pip3 install pyinstaller wheel
          pip3 install .

      - name: Pyinstaller build
        run: |
          pyinstaller build.spec
          cp config.sample.json dist/

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: LiveRecorder_${{ runner.os }}_${{ github.ref_name }}
          path: |
            dist/

      - name: Create archive
        if: startsWith(github.ref_name, 'v')
        uses: thedoctor0/zip-release@main
        with:
          filename: LiveRecorder_${{ runner.os }}_${{ github.ref_name }}.zip
          directory: dist/
          path: |
            LiveRecorder*
            config.sample.json

      - name: Release
        if: startsWith(github.ref_name, 'v')
        uses: ncipollo/release-action@v1
        with:
          artifacts: dist/LiveRecorder*.zip
          allowUpdates: true
          draft: true
          generateReleaseNotes: true
